strategies:
  id1: {enabled: false}
  id2: {enabled: true}
  id3: {enabled: true}
  id4: {enabled: true}
  id5: {enabled: true}
  id6: {enabled: true}
  id7: {enabled: true}
  id8: {enabled: true}
  id9: {enabled: true}
  id10: {enabled: true}
  id11: {enabled: true}
  id12: {enabled: true}
  id13: {enabled: true}
  id14: {enabled: true}
  id15: {enabled: true}
  id16: {enabled: true}
  id17: {enabled: true}
  id18: {enabled: true}
  id19: {enabled: true}
  id20: {enabled: true}
  id21: {enabled: true}
  id22: {enabled: true}
  id23: {enabled: true}
  id24: {enabled: true}
  id25: {enabled: true}
  id26: {enabled: true}
  id27: {enabled: true}
  id28: {enabled: true}
  id29: {enabled: true}
  id30: {enabled: true}
  id31: {enabled: true}
  id32: {enabled: true}
  id33: {enabled: true}
  id34: {enabled: true}
  id35: {enabled: true}
